name: Build and publish binaries

permissions:
  contents: write

on:
  release:
    types: [published]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    if: github.repository_owner == 'Ravencentric' && startsWith(github.event.release.name, 'misaki-cli-v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
            # Linux
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04-arm
          - target: aarch64-unknown-linux-musl
            os: ubuntu-22.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
            # Apple
          - target: x86_64-apple-darwin
            os: macos-13 # Intel
          - target: aarch64-apple-darwin
            os: macos-14 # Arm
            # Windows
          - target: aarch64-pc-windows-msvc
            os: windows-11-arm
          - target: x86_64-pc-windows-msvc
            os: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1.13.0

      - name: Install cross-compilation tools
        if: startsWith(matrix.os, 'ubuntu')
        uses: taiki-e/setup-cross-toolchain-action@0123528f956f923e7a476f4cc04882bc005e7c89 # v1.29.1
        with:
          target: ${{ matrix.target }}

      - uses: taiki-e/upload-rust-binary-action@3962470d6e7f1993108411bc3f75a135ec67fc8c # v1.27.0
        with:
          bin: misaki
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
